## Part 1: Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [ ]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [ ]:
# Create y_df with the Attrition and Department columns
X_df = attrition_df.drop(columns=['Attrition', 'Department'])
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [ ]:
# Create a list of at least 10 column names to use as X data
selected_columns = ['Age', 'DistanceFromHome', 'EnvironmentSatisfaction', 'JobSatisfaction', 'NumCompaniesWorked', 'RelationshipSatisfaction', 'TotalWorkingYears', 'YearsAtCompany',
                    'YearsInCurrentRole', 'YearsWithCurrManager']

# Create X_df using your selected columns
X_df = attrition_df[selected_columns]

# Show the data types for X_df
X_df.dtypes

Age                         int64
DistanceFromHome            int64
EnvironmentSatisfaction     int64
JobSatisfaction             int64
NumCompaniesWorked          int64
RelationshipSatisfaction    int64
TotalWorkingYears           int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsWithCurrManager        int64
dtype: object

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=1)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (1102, 10)
X_test shape: (368, 10)
y_train shape: (1102, 2)
y_test shape: (368, 2)


In [ ]:
missings = X_train.isnull().sum()
print(missings)

Age                         0
DistanceFromHome            0
EnvironmentSatisfaction     0
JobSatisfaction             0
NumCompaniesWorked          0
RelationshipSatisfaction    0
TotalWorkingYears           0
YearsAtCompany              0
YearsInCurrentRole          0
YearsWithCurrManager        0
dtype: int64


In [ ]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (1102, 10)
X_test shape: (368, 10)


In [ ]:

X_train.dtypes

Age                         float32
DistanceFromHome            float32
EnvironmentSatisfaction     float32
JobSatisfaction             float32
NumCompaniesWorked          float32
RelationshipSatisfaction    float32
TotalWorkingYears           float32
YearsAtCompany              float32
YearsInCurrentRole          float32
YearsWithCurrManager        float32
dtype: object

In [ ]:
from re import X
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Scale the training and testing data
print("Scaled Training Data: ", X_train_scaled[:5])
print("Testing Data: ", X_test[:5])

Scaled Training Data:  [[-5.9735338e-04 -1.0093374e+00 -6.6041863e-01  1.1672472e+00
   5.0501585e-01  1.1861737e+00  9.7498521e-02 -1.4217441e-01
   2.1354902e-01 -6.0109246e-01]
 [-1.0977365e+00 -7.6150107e-01 -1.5781757e+00  1.1672472e+00
  -1.0930530e+00  1.1861737e+00 -8.0647212e-01 -4.8314545e-01
  -6.1024684e-01 -8.8502043e-01]
 [-7.6859474e-01  3.5376289e-01 -6.6041863e-01 -1.5891236e+00
  -6.9353575e-01  2.4711953e-01 -1.3230268e+00 -9.9460196e-01
  -1.1594441e+00 -1.1689483e+00]
 [-1.1031126e-01 -2.6582816e-01 -6.6041863e-01  1.1672472e+00
  -2.9401857e-01  2.4711953e-01 -4.1905615e-01 -1.4217441e-01
  -6.1024684e-01 -8.8502043e-01]
 [ 2.0839670e+00 -1.0093374e+00 -1.5781757e+00 -1.5891236e+00
  -2.9401857e-01  1.1861737e+00 -8.0647212e-01 -6.5363097e-01
  -6.1024684e-01 -1.1689483e+00]]
Testing Data:         Age  DistanceFromHome  EnvironmentSatisfaction  JobSatisfaction  \
1291  37.0              10.0                      4.0              1.0   
1153  18.0               3.0

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
department_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
department_trained = department_encoder.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_department_train = department_encoder.transform(y_train[['Department']])
y_department_test = department_encoder.transform(y_test[['Department']])

In [ ]:
print("Y data:", y_department_train[:5])
print("Y data test: ", y_department_test[:5])

Y data: [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]
Y data test:  [[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [ ]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
attrition_train = attrition_encoder.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
y_attrition_train = attrition_encoder.transform(y_train[['Attrition']])
y_attrition_test = attrition_encoder.transform(y_test[['Attrition']])

In [ ]:
print("Y data:", y_attrition_train[:5])
print("Y data test: ", y_attrition_test[:5])

Y data: [[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]
Y data test:  [[0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


## Part 2: Create, Compile, and Train the Model

In [ ]:

# Find the number of columns in the X training data.
input_features = X_train.shape[1]
print(input_features)

# Create the input layer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
model = Sequential()
model.add(Dense(units=10, activation='relu'))

# Create at least two shared layers
model.add(Dense(units=8, activation='softmax'))
model.add(Dense(units=5, activation='softmax'))


10


In [ ]:
# Create a branch for Department
# with a hidden layer and an output layer
department_input = Input(shape=(input_features,))

# Create the hidden layer
department_hidden = Dense(units=10, activation='relu')(department_input)

# Create the output layer
department_output = Dense(units=3, activation='softmax')(department_hidden)


In [ ]:
# Create a branch for Attrition
# with a hidden layer and an output layer
attrition_input = Input(shape=(input_features,))
# Create the hidden layer
attrition_hidden = Dense(units=10, activation='relu')(attrition_input)

# Create the output layer
attrition_output = Dense(units=2, activation='softmax')(attrition_hidden)

In [ ]:
# Create the model
model = Model(inputs=[department_input, attrition_input], outputs=[department_output, attrition_output])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=[['accuracy'], ['accuracy']])

# Summarize the model
model.summary()

Model: "functional_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_18            │ (None, 10)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ input_layer_19            │ (None, 10)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_49 (Dense)          │ (None, 10)             │            110 │ input_layer_18[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_51 (Dense)          │ (None, 10)             │            110 │ input_layer_19[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_50 (Dense)          │ (None, 3)              │             33 │ dense_49[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_52 (Dense)          │ (None, 2)              │             22 │ dense_51[0][0]         │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 275 (1.07 KB)

 Trainable params: 275 (1.07 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Train the model
history = model.fit([X_train_scaled, X_train_scaled], [y_department_train, y_attrition_train], epochs=100, batch_size=32)

Epoch 1/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - dense_50_accuracy: 0.4001 - dense_50_loss: 1.1443 - dense_52_accuracy: 0.6342 - dense_52_loss: 0.7056 - loss: 1.8501
Epoch 2/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - dense_50_accuracy: 0.5333 - dense_50_loss: 0.9909 - dense_52_accuracy: 0.7090 - dense_52_loss: 0.6044 - loss: 1.5954
Epoch 3/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - dense_50_accuracy: 0.5984 - dense_50_loss: 0.9331 - dense_52_accuracy: 0.7586 - dense_52_loss: 0.5528 - loss: 1.4857
Epoch 4/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - dense_50_accuracy: 0.6188 - dense_50_loss: 0.8672 - dense_52_accuracy: 0.7892 - dense_52_loss: 0.5100 - loss: 1.3772
Epoch 5/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - dense_50_accuracy: 0.6032 - dense_50_loss: 0.8732 - dense_52_accuracy: 0.8178 - dense_52_loss: 0.4947 - loss: 1.3679
Epoch 6/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - dense_50_accuracy: 0.6307 - dense_50_loss: 0.8481 - dense_52_accuracy: 0.8190 - dense_52_loss: 0.

In [ ]:
# Evaluate the model with the testing data
eval_results = model.evaluate([X_test_scaled, X_test_scaled], [y_department_test, y_attrition_test])

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - dense_50_accuracy: 0.6270 - dense_50_loss: 0.8448 - dense_52_accuracy: 0.8087 - dense_52_loss: 0.4626 - loss: 1.3098  


In [ ]:
# Print the accuracy for both department and attrition
print("Department Accuracy:", eval_results[0])
print("Attrition Accuracy:", eval_results[1])

Department Accuracy: 1.2449954748153687
Attrition Accuracy: 0.7786888480186462


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy may not be the best metric if the dataset is imbalanced. In some cases, metricts like predision, recall, F1-score could provide better understanding of the model's performance.
2. I tried both the binary and categorical crossentropy, and both the sigmoid and softmax activation. The categorical_crossentropy with the softmax activation provided the highest accuracy scores. The other scores were categorical, sigmoid Department 1.234, Attrition .774; binary, sigmoid - Department .932 Attrition .489; binary, softmax - Department .952 Attrition .486
3. I would try changing the select features to possibly improve the input data's quality and could also try hyperparameter tuning such as experimenting with the number of neurons, layers and batch sizes.