## Part 1: Preprocessing

In [42]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [43]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [44]:
# Create y_df with the Attrition and Department columns
X_df = attrition_df.drop(columns=['Attrition', 'Department'])
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [45]:
# Create a list of at least 10 column names to use as X data
selected_columns = ['Age', 'DistanceFromHome', 'EnvironmentSatisfaction', 'JobSatisfaction', 'NumCompaniesWorked', 'RelationshipSatisfaction', 'TotalWorkingYears', 'YearsAtCompany',
                    'YearsInCurrentRole', 'YearsWithCurrManager']

# Create X_df using your selected columns
X_df = attrition_df[selected_columns]

# Show the data types for X_df
X_df.dtypes

Age                         int64
DistanceFromHome            int64
EnvironmentSatisfaction     int64
JobSatisfaction             int64
NumCompaniesWorked          int64
RelationshipSatisfaction    int64
TotalWorkingYears           int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsWithCurrManager        int64
dtype: object

In [46]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=1)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (1102, 10)
X_test shape: (368, 10)
y_train shape: (1102, 2)
y_test shape: (368, 2)


In [47]:
missings = X_train.isnull().sum()
print(missings)

Age                         0
DistanceFromHome            0
EnvironmentSatisfaction     0
JobSatisfaction             0
NumCompaniesWorked          0
RelationshipSatisfaction    0
TotalWorkingYears           0
YearsAtCompany              0
YearsInCurrentRole          0
YearsWithCurrManager        0
dtype: int64


In [48]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (1102, 10)
X_test shape: (368, 10)


In [49]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Scale the training and testing data
print("Scaled Training Data: ", X_train_scaled[:5])
print("Scaled Testing Data: ", X_test_scaled[:5])

Scaled Training Data:  [[-5.9735338e-04 -1.0093374e+00 -6.6041863e-01  1.1672472e+00
   5.0501585e-01  1.1861737e+00  9.7498521e-02 -1.4217441e-01
   2.1354902e-01 -6.0109246e-01]
 [-1.0977365e+00 -7.6150107e-01 -1.5781757e+00  1.1672472e+00
  -1.0930530e+00  1.1861737e+00 -8.0647212e-01 -4.8314545e-01
  -6.1024684e-01 -8.8502043e-01]
 [-7.6859474e-01  3.5376289e-01 -6.6041863e-01 -1.5891236e+00
  -6.9353575e-01  2.4711953e-01 -1.3230268e+00 -9.9460196e-01
  -1.1594441e+00 -1.1689483e+00]
 [-1.1031126e-01 -2.6582816e-01 -6.6041863e-01  1.1672472e+00
  -2.9401857e-01  2.4711953e-01 -4.1905615e-01 -1.4217441e-01
  -6.1024684e-01 -8.8502043e-01]
 [ 2.0839670e+00 -1.0093374e+00 -1.5781757e+00 -1.5891236e+00
  -2.9401857e-01  1.1861737e+00 -8.0647212e-01 -6.5363097e-01
  -6.1024684e-01 -1.1689483e+00]]
Scaled Testing Data:  [[-5.9735338e-04  1.0592646e-01  1.1750956e+00 -1.5891236e+00
  -6.9353575e-01 -6.9193465e-01 -1.6077881e-01  5.3976768e-01
  -3.3564824e-01  1.1024752e+00]
 [-2.0851617

In [50]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
department_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
department_trained = department_encoder.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_department_train = department_encoder.transform(y_train[['Department']])
y_department_test = department_encoder.transform(y_test[['Department']])

In [51]:
print("Y data:", y_department_train[:5])
print("Y data test: ", y_department_test[:5])

Y data: [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]
Y data test:  [[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [52]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder()

# Fit the encoder to the training data
attrition_train = attrition_encoder.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
y_attrition_train = attrition_encoder.transform(y_train[['Attrition']])
y_attrition_test = attrition_encoder.transform(y_test[['Attrition']])

In [53]:
print("Y data:", y_attrition_train[:5])
print("Y data test: ", y_attrition_test[:5])

Y data:   (0, 0)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
Y data test:    (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 0)	1.0


## Part 2: Create, Compile, and Train the Model

In [56]:

# Find the number of columns in the X training data.
input_features = X_train.shape[1]
print(input_features)

# Create the input layer
model = Sequential()
model.add(Dense(units=10, activation='relu', input_dim=input_features))

# Create at least two shared layers
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=5, activation='relu'))


10


In [55]:
# Create a branch for Department
# with a hidden layer and an output layer
department_input = Input(shape=(input_features,))

# Create the hidden layer
department_hidden = Dense(units=10, activation='relu')(department_input)

# Create the output layer


NameError: name 'Input' is not defined

In [ ]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer


In [ ]:
# Create the model


# Compile the model


# Summarize the model


In [ ]:
# Train the model


In [ ]:
# Evaluate the model with the testing data


In [ ]:
# Print the accuracy for both department and attrition


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1.
2.
3.